addEvent("GTARP:LoginSuccessful", true)
addEventHandler("GTARP:LoginSuccessful", root, function(characterData)
    if characterData then
        setCharacterData(characterData.id, "owner_uid", characterData.owner_id)
        setCharacterData(characterData.id, "name", string.gsub(characterData.name, "_", " "))
        setCharacterData(characterData.id, "age", characterData.age)
        setCharacterData(characterData.id, "height", characterData.height)
        setCharacterData(characterData.id, "weigth", characterData.weight)
        setCharacterData(characterData.id, "eye_color", characterData.eye_color)
        setCharacterData(characterData.id, "status", characterData.status)
        setCharacterData(characterData.id, "gender", characterData.gender)
        setCharacterData(characterData.id, "money", characterData.bank_money)
        setCharacterData(characterData.id, "skin", characterData.skin)
        setCharacterData(characterData.id, "hp", characterData.hp)
        setCharacterData(characterData.id, "last_x", characterData.last_x)
        setCharacterData(characterData.id, "last_y", characterData.last_y)
        setCharacterData(characterData.id, "last_z", characterData.last_z)
        setCharacterData(characterData.id, "rotation", characterData.rotation)
        setCharacterData(characterData.id, "vw", characterData.vw)
    end
end)